version: "3.0"

services:
  shiny:
    container_name: covidtracker
    # To build the image locally, comment out "image" below, and uncomment
    # "build" and the lines indented under it.
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # Setting this to something other than 'root' will cause shiny apps not to
    # run on the localhost:80 "Welcome to Shiny" diagnostics page mentioned
    # below.
    user: 'root'
    # Uncomment the lines below to disable application logs STDOUT output
    # environment:
    #   - APPLICATION_LOGS_TO_STDOUT=false
    # ports:
    #   - '3838:3838'
    volumes:
      - ./shiny_logs:/var/log/shiny-server
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.covidtracker.entrypoints=secure"
        - "traefik.http.routers.covidtracker.rule=Host(`covidtracker.$DOMAIN`)"
        - "traefik.http.services.covidtracker.loadbalancer.server.port=3838"
        - "traefik.http.routers.covidtracker.tls.certresolver=le"

networks:
    default:
        external:
            name: $DEFAULT_NETWORK
